let sanitize_ident name =
  let b = Buffer.create (String.length name) in
  String.iter
    (fun ch ->
      let valid =
        (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z')
        || (ch >= '0' && ch <= '9') || ch = '_'
      in
      Buffer.add_char b (if valid then ch else '_'))
    name;
  let out = Buffer.contents b in
  if out = "" then "unnamed"
  else if out.[0] >= '0' && out.[0] <= '9' then "_" ^ out
  else out

let cstruct_name name = "xi_cstruct_" ^ sanitize_ident name

let c_type ?(field = false) = function
  | Ast.Int (Some 8) -> "int8_t"
  | Ast.Int (Some 16) -> "int16_t"
  | Ast.Int (Some 32) -> "int32_t"
  | Ast.Int (Some 64) -> "int64_t"
  | Ast.Uint (Some 8) -> "uint8_t"
  | Ast.Uint (Some 16) -> "uint16_t"
  | Ast.Uint (Some 32) -> "uint32_t"
  | Ast.Uint (Some 64) -> "uint64_t"
  | Ast.Dec (Some 16) -> "_Float16"
  | Ast.Dec (Some 32) -> "float"
  | Ast.Dec (Some 64) -> "double"
  | Ast.Str -> "const char *"
  | Ast.Bool -> "_Bool"
  | Ast.Named "cptr" -> "void *"
  | Ast.Named "void" -> "void"
  | Ast.Named name -> cstruct_name name ^ if field then "" else " *"
  | _ -> "void *"

let escape_line_path path =
  let b = Buffer.create (String.length path) in
  String.iter
    (function
      | '\\' -> Buffer.add_string b "\\\\"
      | '"' -> Buffer.add_string b "\\\""
      | ch -> Buffer.add_char b ch)
    path;
  Buffer.contents b

let line_of_offset path offset =
  try
    let source = In_channel.with_open_bin path In_channel.input_all in
    let limit = min offset (String.length source) in
    let line = ref 1 in
    for i = 0 to limit - 1 do
      if source.[i] = '\n' then incr line
    done;
    !line
  with Sys_error _ -> 1

let emit_line_directive b origin line offset =
  match origin with
  | None -> ()
  | Some path ->
      let line =
        match line with
        | Some line -> line
        | None -> line_of_offset path offset
      in
      Buffer.add_string b
        (Printf.sprintf "#line %d \"%s\"\n"
           line
           (escape_line_path path))

let generate (program : Ast.program) =
  if program.c_preambles = [] && program.c_functions = [] then None
  else begin
    let b = Buffer.create 4096 in
    Buffer.add_string b
      "/* Generated by xic from inline C blocks. */\n#include <stdint.h>\n#include <stdbool.h>\n#include <stddef.h>\n\n";

    let cstructs =
      List.filter (fun (decl : Ast.struct_decl) -> decl.c_layout) program.structs
    in
    List.iter
      (fun (decl : Ast.struct_decl) ->
        Buffer.add_string b
          (Printf.sprintf "typedef struct %s %s;\n"
             (cstruct_name decl.name) (cstruct_name decl.name)))
      cstructs;
    if cstructs <> [] then Buffer.add_char b '\n';

    let by_name = List.map (fun (decl : Ast.struct_decl) -> decl.name, decl) cstructs in
    let emitted = Hashtbl.create 16 in
    let rec emit_cstruct (decl : Ast.struct_decl) =
      if not (Hashtbl.mem emitted decl.name) then begin
        List.iter
          (fun (field : Ast.struct_field_decl) ->
            match field.ty.kind with
            | Ast.Named name ->
                (match List.assoc_opt name by_name with Some nested -> emit_cstruct nested | None -> ())
            | _ -> ())
          decl.fields;
        Hashtbl.add emitted decl.name ();
        Buffer.add_string b (Printf.sprintf "struct %s {\n" (cstruct_name decl.name));
        List.iter
          (fun (field_decl : Ast.struct_field_decl) ->
            Buffer.add_string b
              (Printf.sprintf "    %s %s;\n"
                 (c_type ~field:true field_decl.ty.kind)
                 (sanitize_ident field_decl.name)))
          decl.fields;
        Buffer.add_string b "};\n\n"
      end
    in
    List.iter emit_cstruct cstructs;

    List.iter
      (fun (preamble : Ast.c_preamble_decl) ->
        emit_line_directive b preamble.origin preamble.line preamble.body_offset;
        Buffer.add_string b preamble.body;
        if preamble.body = "" || preamble.body.[String.length preamble.body - 1] <> '\n'
        then Buffer.add_char b '\n';
        Buffer.add_char b '\n')
      program.c_preambles;

    List.iter
      (fun (fn : Ast.inline_c_fn_decl) ->
        let params =
          fn.params
          |> List.map (fun (p : Ast.param) ->
                 Printf.sprintf "%s %s" (c_type p.ty.kind) (sanitize_ident p.name))
          |> String.concat ", "
        in
        Buffer.add_string b
          (Printf.sprintf "%s %s(%s) {\n"
             (c_type fn.return_ty.kind) (sanitize_ident fn.symbol)
             (if params = "" then "void" else params));
        emit_line_directive b fn.origin fn.line fn.body_offset;
        Buffer.add_string b fn.body;
        if fn.body = "" || fn.body.[String.length fn.body - 1] <> '\n'
        then Buffer.add_char b '\n';
        Buffer.add_string b "}\n\n")
      program.c_functions;
    Some (Buffer.contents b)
  end
