let () =
  let var = Sys.argv.(1) in
  let input = Sys.argv.(2) in
  let output = Sys.argv.(3) in
  let ic = open_in_bin input in
  let n = in_channel_length ic in
  let data = really_input_string ic n in
  close_in ic;
  let oc = open_out_bin output in
  output_string oc "(* Generated by tools/gen_embed.ml -- do not edit. *)\n";
  Printf.fprintf oc "let %s = String.concat \"\" [\n" var;
  let chunk_size = 16 * 1024 in
  let rec write_chunks offset =
    if offset < n then begin
      let len = min chunk_size (n - offset) in
      Printf.fprintf oc "  %S;\n" (String.sub data offset len);
      write_chunks (offset + len)
    end
  in
  write_chunks 0;
  output_string oc "]\n";
  close_out oc
