let has_xi_suffix path =
  Filename.check_suffix (String.lowercase_ascii path) ".xi"

let read_file path =
  let ic = open_in_bin path in
  let length = in_channel_length ic in
  let contents = really_input_string ic length in
  close_in ic;
  contents

let () =
  if Array.length Sys.argv <> 3 then begin
    prerr_endline "usage: gen_std_embed.ml <std-dir> <output.ml>";
    exit 2
  end;
  let input_dir = Sys.argv.(1) in
  let output = Sys.argv.(2) in
  let files =
    Sys.readdir input_dir
    |> Array.to_list
    |> List.filter has_xi_suffix
    |> List.sort String.compare
  in
  let oc = open_out_bin output in
  output_string oc "(* Generated by tools/gen_std_embed.ml -- do not edit. *)\n";
  output_string oc "let modules = [\n";
  List.iter
    (fun file ->
      let name = Filename.remove_extension file in
      let source = read_file (Filename.concat input_dir file) in
      Printf.fprintf oc "  (%S, %S);\n" name source)
    files;
  output_string oc "]\n\n";
  output_string oc "let find name = List.assoc_opt name modules\n";
  close_out oc
